name: Build
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
          bundler: 2.2.17

      - uses: actions/setup-node@v3
        with:
          node-version: '12.22.5'
          cache: 'yarn'

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Migrate database
        run: bundle exec rails db:migrate

      - name: Run test
        run: bundle exec rails test

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    if: github.ref == 'refs/heads/main"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
